spring:
  application:
    name: Registre

  datasource:
    url: jdbc:postgresql://dvregistrylg001.ad.insee.intra:1983/di_pg_registry_dv01
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
